### ISSUE TITLE
Getting PostgreSQL tests to green

### ISSUE THREAD

**Issue by benilovj** [dbfit/dbfit#1]

**Comment by MMatten** [comment]
For the remaining Postgres test what's to be done. DbFit 1.1 used to support the table name in the second fixture table row (http://sourceforge.net/p/dbfit/code/HEAD/tree/tags/dbfit-1.x/impl/java/src/dbfit/fixture/Insert.java#l30) but there's no evidence of this being attempted in the 2.x code.

Do we delete the test (and the same in the Oracle tests) and formally drop this?

**Comment by javornikolov** [comment]
Resolved by #373, #377
