### ISSUE TITLE
Push DbFit jars to Maven Central

### ISSUE THREAD

**Issue by benilovj** [dbfit/dbfit#173]
Here's [how to do it with Gradle](http://jedicoder.blogspot.com/2011/11/automated-gradle-project-deployment-to.html).

**Comment by MMatten** [comment]
Chaps, if we got this done do you think it would make sense to get the Fitnesse project to include some basic DbFit regression/smoke tests (may be the Derby or HSQL tests) to ensure compatibility or are projects generally having to fall into line with what that project does?

**Comment by benilovj** [comment]
> Chaps, if we got this done do you think it would make sense to get the Fitnesse project to include some basic DbFit regression/smoke tests (may be the Derby or HSQL tests) to ensure compatibility or are projects generally having to fall into line with what that project does?

I think that this is really a question for the Fitnesse folks. If they're interested in having a CI build running which integrates the last released DBFit with their latest master, that should be fairly easy to set up.

**Comment by MMatten** [comment]
I might suggest this via the Yahoo group then and see what comes back.

**Comment by MMatten** [comment]
And I guess a single Jar file would be better than the separate core and adapter Jars.

**Comment by MMatten** [comment]
I've put up a speculative request on Sonatype.org using the `com.neuri` groupId:

https://issues.sonatype.org/browse/OSSRH-16266?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel 

It's been questioned, rightly. What groupId should be used seeing as there's no `org.dbfit` or similar that this project owns? They've pitched `com.github.dbfit` as possible.

I guess this wouldn't affect the package names in the code or should those be aligned? E.g. `com.github.dbfit.fixture.Clean`?

**Comment by benilovj** [comment]
> They've pitched com.github.dbfit as possible.
:+1: as a groupId

However I don't think this is a good enough reason to change the package structure, since that would break everyone...
