### ISSUE TITLE
add getAutoCommit() check before setAutoCommit

### ISSUE THREAD

**Issue by struesda** [dbfit/dbfit#330]
I was trying to create a separate pull request - but then saw you had done #327 already.

In my fork - I also added calls to getAutoCommit() around setAutoCommit in AbstractDbEnvironment.   This is a standard JDBC method and should make it easier to handle non-transactional databases.

However - I am not familiar enough with git to know how to make a new pull request from my fork with just these changes.

At the moment I have manually removed the Informix changes from my fork - but am still trying to figure out how to create a new pull request.

Let me know the best way to proceed.

**Comment by javornikolov** [comment]
Closing this as it's supposed to be possible to achieve the desired behavior with the functionality added with #385.
