### ISSUE TITLE
Stored Proc implicit return value SQL Server 2014

### ISSUE THREAD

**Issue by OB4** [dbfit/dbfit#351]
If I try the following code, I get a cast-error. It isn't possible to cast from system.DateTime to system.TimeSpan:

!|Insert|dbo.Zeit|
|Zeit|
|08:10:00|

What goes wrong?

**Comment by javornikolov** [comment]
@OB4 , could you please share the exact error message and stack you're getting. An also the table definition - what's the exact data type of Zeit column in the database?

**Comment by OB4** [comment]
To show  the error I have a simple table definition:
Id (PS, int, Not null)
Zeit (time(7), NULL)

Here the test:
!|Insert|dbo.Zeit|
|Zeit|
|08:00:00|

The exact error message:

System.InvalidCastException: Parameterwert konnte nicht von DateTime in TimeSpan umgewandelt werden. ---> System.InvalidCastException: Ungültige Umwandlung von "System.DateTime" in "System.TimeSpan".
   bei System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   bei System.DateTime.System.IConvertible.ToType(Type type, IFormatProvider provider)
   bei System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   bei System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   bei System.Data.SqlClient.SqlParameter.GetCoercedValue()
   bei System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   bei System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
   bei System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   bei System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   bei System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bei fit.ColumnFixture.DoRow(Parse row)

**Comment by javornikolov** [comment]
Hi @OB4, seems you're using the .NET version of DbFit which is maintained as separate project  http://www.syterra.com/FitSharp.html

Does the same persist with the java version?

**Comment by OB4** [comment]
Hello @javornikolov, I install the java version. It was a lot of work to find all things. Now it is running. The time-Type is now no problem but my other Stored-Procedure-Tests throws the following error:

java.sql.SQLException: Cannot find parameter ""
	at dbfit.api.DbStoredProcedure.findAccessorForParamWithName(DbStoredProcedure.java:51)
	at dbfit.api.DbStoredProcedure.getDbParameterAccessor(DbStoredProcedure.java:32)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:121)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:108)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:71)
	at fit.Fixture.doTable(Fixture.java:155)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:18)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:99)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:87)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:69)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:34)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

Here is the dbfit-Test:
!|Execute Procedure|dbo.AufgabentraegerDelete|
|id|rv|?|
|<<id2|<<rv2|0|
It don't find the Id-Parameter. With the .net-Version all works fine.

**Comment by javornikolov** [comment]
What is the stored procedure (dbo.AufgabentraegerDelete) definition; at least the header - parameters and return type.

**Comment by javornikolov** [comment]
Also the output of following query which is being used to extract procedure parameters from the database:
``` sql
select
    c.[name], TYPE_NAME(c.system_type_id) as [Type], c.max_length, c.column_id
from
    sys.columns c
where
    c.object_id = OBJECT_ID([dbo].[aufgabentraegerdelete])
order by
    c.column_id
```

**Comment by OB4** [comment]
Here the definition:
ALTER PROCEDURE [dbo].[AufgabentraegerDelete] (@id INT, @rv ROWVERSION)

If I execute the query with "aufgabentraegerdelete" there is no result. With the underlying table I get the following result:
Id	   int               4   1
Name  nvarchar   80   2
RV      timestamp   8   3

With other Stored Procedures I have the same problems.

**Comment by javornikolov** [comment]
Hi @OB4,

The problem is that the anonymous parameter definition `|?|` is expecting a function definition. While the stored proc definition and the metadata query don't indicate any return value (which is expected to be named with empty string but should still have data type).

**Comment by OB4** [comment]
Hello @javornikolov, I need the anonymous parameter for the return-value, which is always an integer in SQL Server, of the stored procedure. With the .net-version there is no problem. Would it be possible to change it in the jave-version? Many thanks for the help!

**Comment by javornikolov** [comment]
I took a look at the [code of the .net version](/jediwhale/fitsharp/blob/bc7174ccee25045f28d22a5671effe5676213395/source/dbfitSqlServer/SqlServerEnvironment.cs#L44-45).

I'll modify the Java version soon, it seems pretty straightforward to fix that.

**Comment by javornikolov** [comment]
Hi @OB4, could you try [this preliminary build](https://s3.amazonaws.com/dbfit/artifacts/57707764/57707766/dbfit-complete-3.1.0.zip) to check if it solves the problem?

Also would be great if you can check if the test in FitNesseRoot/DbFit/AcceptanceTests/DotNetTests/SqlServerTests/FlowMode/SimpleStoredProc/content.txt is working OK.

I don't have MS SQL Server environment right now so it would be great if you can test the above.

**Comment by OB4** [comment]
I wrote 2 tests:
!|Execute Procedure|dbo.CalcLength_P|
|name|str length?|?|
|mika|4|-2|
This test is OK.

!|Execute Procedure  expect exception|dbo.CalcLength_P|
|name|str length?|?|
|throw execption|15|-1|
This test don't return a value - only a blank!!!
In the net-version the correct value is returned.

Here the test-procedure in T-SQL:

ALTER PROCEDURE [dbo].[CalcLength_P] (@Name NVARCHAR(40),@strlength INT OUTPUT)
AS
BEGIN
	SET NOCOUNT ON;

	SET @strlength = Len(@Name);

	IF (@Name = 'throw execption')
	BEGIN
		RAISERROR ('Execption thrown', 16, 1);
		RETURN -1;
	END
	RETURN -2;
END

**Comment by javornikolov** [comment]
I'm not sure how exactly does exception raising work in T-SQL but that case sounds a bit weird. Normally I would expect raising an exception to abort the flow (i.e. - that "return -1" not to be reached at all). So I wonder - what should be the stored proc implicit return value in case of thrown exception?

**Comment by OB4** [comment]
Hello @javornikolov , In the .net-version it works correctly. That's the only thing I can say.

**Comment by javornikolov** [comment]
Is the case with `throw exception` indicating that an exception has been thrown? What happens if you use:
```
!|Execute Procedure|dbo.CalcLength_P|
|throw execption|15|-1|
```

**Comment by OB4** [comment]
No matter which return-value I use, the tests always green, because there is no return-value of a procedure which throws an exception. See below the screenshot:

![execute procedure calclength_p](https://cloud.githubusercontent.com/assets/11805811/7101084/e38d1578-e044-11e4-8a5a-d42c36efb2c5.gif)

**Comment by javornikolov** [comment]
@OB4, could you please also provide the output of Execute Procedure (**without** `expect exception`) with name=`throw exception`?

**Comment by OB4** [comment]
Here is the screenshot:

![calclength_p](https://cloud.githubusercontent.com/assets/11805811/7105076/096bee14-e107-11e4-91b4-222c809c214e.gif)

In the .net-Version it uses a SqlCommand object and adds an additional parameter with an empty name and later set the name to "Parameter1". Here are the screenshots from VS2010:
![sqlcommand](https://cloud.githubusercontent.com/assets/11805811/7105098/d6eed7b6-e107-11e4-9b75-66c20850835a.gif)
![sqlparameter](https://cloud.githubusercontent.com/assets/11805811/7105101/e0eb89f8-e107-11e4-8e04-907ca0453fa2.gif)

**Comment by javornikolov** [comment]
Hi @OB4, could you check what's the behaviour of .NET version when the exception is raised via `throw` statement?

Some open questions:
* I'm looking into an article about [`throw` vs `raiseerror`](http://sqlhints.com/2013/06/30/differences-between-raiserror-and-throw-in-sql-server/). I'm not sure if there is a way a caller to distinguish whether the error has been raised using `raiseerror` or `throw`. In the latter case return values are irrelevant since explicit `return` statements are never reached.
* I don't know whether the MS SQL JDBC driver is setting any output parameters and return values in case of exception.

**Comment by OB4** [comment]
Hallo @javornikolov, if I use throw instead of raiseerror in .NET version, the return-value is null. Now I think it's better to use throw  in the future and I don't get a return-value.
