### ISSUE TITLE
Transactions error for Teradata Stored Procedure with DDL

### ISSUE THREAD

**Issue by z0diak** [dbfit/dbfit#383]
There is a problem with 3.10 when I try to test Teradata stored procedure with several DDL statements inside. 
How it can be reproduced:
SQL for Procedure:
```sql
REPLACE PROCEDURE IssueWithTransactions(out sampleout char(4))
begin
	DECLARE sql_query VARCHAR(4000);
	SET sql_query='create table iwt_table1 (fakefield integer)';
	call DBC.SysExecSQL (sql_query);
	SET sql_query='alter table iwt_table1 add fakefield2 integer';
	call DBC.SysExecSQL (sql_query);
	SET sql_query='alter table iwt_table1 add fakefield3 integer';
	call DBC.SysExecSQL (sql_query);
	SET sampleout='true';
end;
```
And here is DbFit code for test:
Call procedure
!|Execute Procedure|dftest.IssueWithTransactions|
|sampleout?|
|true|

Result is java exception:
java.sql.SQLException: [Teradata Database] [TeraJDBC 15.10.00.05] [Error 3932] [SQLState 25000] ISSUEWITHTRANSACTIONS:Only an ET or null statement is legal after a DDL Statement.

Connection mode: /TMODE=TERA
Exception tells us that transaction was started and must be finished after first DDL to keep possibility to run next DDL. 
This is Teradata specifics and DbFit perfectly handles it for "Execute Ddl" fixture.

**Here is some diagnostics**
If I modify stored procedure and add "ET;" statement:
```sql
REPLACE PROCEDURE IssueWithTransactions(out sampleout char(4))
begin
	DECLARE sql_query VARCHAR(4000);
	SET sql_query='create table iwt_table1 (fakefield integer)';
	call DBC.SysExecSQL (sql_query);
	ET;	
	SET sql_query='alter table iwt_table1 add fakefield2 integer';
	call DBC.SysExecSQL (sql_query);
	SET sql_query='alter table iwt_table1 add fakefield3 integer';
	call DBC.SysExecSQL (sql_query);
	SET sampleout='true';
end;
```
then DbFit test works fine, because I explicitly close transaction. But the thing is - I didn't started that transaction. So if I try to execute this procedure outside of DbFit (from Teradata SQL Assistant for example) it will fail with message that I try to End Transaction which wasn't started. 

I'm not a java developer, but it looks for me that Execute Procedure fixture explicitly starts transaction in any case. Even if it's not needed.
Or - other suggestion - autocommit mode is explicitly off. But for /TMODE=TERA connection mode autocommit must work (that is the major point of this mode).
Teradata JDBC adapter docs (https://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html) tells that for TERA mode it will work in following way:
_If the caller's session has Teradata transaction semantics, then the Java XSP's default connection Auto-Commit setting will depend on whether the caller's session is within an existing transaction (for example, BT was executed). In this case, the Auto-Commit setting will be false if BT was executed, and the Auto-Commit setting will be true if BT was not executed._

So it looks (suggestion) that BT (Begin Transaction) is fired before executing procedure.
But for Teradata it would be logical to check connection mode and (ANSI vs TERA) and then leave transaction semantics to Teradata.

**Comment by javornikolov** [comment]
A few more things coming to my mind in relation to that issue:
* Check how it behaves in Standalone mode. (The main idea of Flow mode is that it runs the whole test page in single transaction and rolls it back at the end. Committing/rolling-back the transaction in the middle of the test or executing DDL is not a very typical use case).
* Consider adding ability to explicitly set auto-commit on/off
* Does Teradata support something like Oracle's autonomous transactions? It might be handy to devise some workaround.

In general it should be possible not to explicitly set auto-commit for Teradata. (Just I'm not sure why we have set autocommit=false after each commit /for all database types; and whether it's safe to remove that).

**Comment by z0diak** [comment]
Checked Standalone mode - same behavior
I also vote for ability to explicitly set autocommit in tests and use default driver autocommit as start. 

Actually in Teradata I can manage transaction logic by choosing connection mode - TERA or ANSI. And DbFit Connect Fixture supports it. So as Teradata developer I know which behavior I should expect for each mode and choose proper. But explicit autocommit off here (dbfit-java/core/src/main/java/dbfit/DatabaseTest.java) prevents Teradata JDBC driver to act as expected.

**Comment by MMatten** [comment]
If an option was introduced then I'd vote here for having the default (initial) state as auto commit = false. This is what Flow Mode (probably the most commonly used mode) is all about.

**Comment by javornikolov** [comment]
Hi @z0diak, @MMatten - I added support for `setAutoCommit` in #385 (not merged yet). Would you be able to test if it's good enough to resolve the issue? There is a test build [here](https://s3.amazonaws.com/dbfit/artifacts/69597165/69597166/dbfit-complete-3.1.0.zip).

If you manage to test on other kinds of databases - would be appreciated. (So far I've tested it on derby and hsqldb only).

**Comment by z0diak** [comment]
@javornikolov great news! tested my scenario with this build and TERA connection mode:
 * Original scenario with no changes reported in first post - reproduced, error exists
 * FlowMode, autocommit = false - error exists (correct)
 * FlowMode, autocommit = true - no error, test passes
 * StandaloneMode, autocommit = false  - error exists (correct)
 * StandaloneMode, autocommit = true - no error, test passes
Also I did test it with ANSI connection mode - all combinations failed with proper error messages (because if I use ANSI mode then I must explicitly commit all work inside Stored Procedure). 
As for me - this feature solves the problem. 
Unfortunately I don't have any DB VM except Teradata at my hands, so can't test on other DB's quickly.

**Comment by javornikolov** [comment]
@z0diak, thank you very much for the feedback! It's good to know that this approach is solving the problem.

Some implementation details are still under discussion - e.g. whether to make this feature for standalone mode only and others. Do you have ha need to use this in Flow Mode or standalone mode will be sufficient?

**Comment by z0diak** [comment]
@javornikolov I'm a bit new to DbFit, but as far as I understand Flow Mode is all about one test = one transaction. If autocommit enabled, it means that all, e.g. inserts done for data preparation, will be commited also. Which automatically means Flow Mode became Standalone mode, where test-creator must handle transactions manually. And must clean up all generated-by-test data manually also. 
I may not be aware of other Flow Mode vs Standalone mode limitations (didn't find in docs), but from this perspective I think there is no need to autocommit in Flow Mode because it could kill whole idea.
