### ISSUE TITLE
Add missing SQL Server data types

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#386]
Binary types: 
- ROWVERSION
- TIMESTAMP
- BINARY
- VARBINARY
- IMAGE

**Comment by Auguronomics** [comment]
MS Jdbc documentation and how-to 
https://msdn.microsoft.com/en-us/library/ms378813(v=sql.110).aspx

**Comment by JeremyCarlsten** [comment]
Any update on this?
