### ISSUE TITLE
Type LONG is not supported

### ISSUE THREAD

**Issue by z0diak** [dbfit/dbfit#387]
We have an issue with testing Teradata stored procedures that have BIGINT data type as out parameter.
"Execute procedure" fixture throws exception:
java.lang.UnsupportedOperationException: TeradataEnvironment: getSqlType: Type LONG is not supported.
I believe there are set of Teradata database data types that treated as Java LONG data type.
It would be good to have these data types supported too.

**Comment by MMatten** [comment]
It looks like the methods `getAllProcedureParameters` and `getAllColumns` are out of sync in `TeradataEnvironment.java`.

I think DbFit will handle tables containing BIGINT columns but not in stored procs.

I'll try that change and create a PR if it works.

**Comment by MMatten** [comment]
@z0diak,

I've created a pull request for a fix for this issue but I can't provide you a distribution. 

Perhaps @javornikolov can help again if this gets merged.

**Comment by javornikolov** [comment]
@z0diak - you may try the fix using the following [test build](https://s3.amazonaws.com/dbfit/artifacts/70029673/70029676/dbfit-complete-3.1.0.zip).

**Comment by MMatten** [comment]
Do you think it's worth considering a 3.1.1 release soon or allow people to access to dev snapshots

**Comment by javornikolov** [comment]
Yes, we can make a new release soon.

**Comment by z0diak** [comment]
@MMatten @javornikolov thanks, fix works!
