### ISSUE TITLE
Test VM build fails - `Cheffile` and `Cheffile.lock` out of sync error

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#391]
`vagrant up` produces: -

C:/Users/MMatten/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:32:in `check_consistent': Cheffile and Cheffile.lock are out of sync! (Librarian::Error)

Deleting `Cheffile.lock` allows the `vagrant up` to complete although there are also errors in the DB2 installation: -

==> default: [2015-07-11T12:50:44+00:00] INFO: service[postgresql] restarted
==> default: [2015-07-11T12:50:44+00:00] ERROR: Running exception handlers
==> default: [2015-07-11T12:50:44+00:00] ERROR: Exception handlers complete
==> default: [2015-07-11T12:50:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-07-11T12:50:44+00:00] ERROR: execute[install DB2 package if available] (dbfit_test::db2 line 10) had an error: Mi
xlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 2, 3], but received '1'
==> default: ---- Begin output of /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl ----
==> default: STDOUT: install_db2.sh: INFO: found gzipped installation tarball. Unpacking...
==> default: STDERR: tar: expc/db2/linuxamd64/install/libdb2ure.so: Cannot create symlink to `libdb2ure.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2install_install.so: Cannot create symlink to `libdb2install_install.so.1': Proto
col error
==> default: tar: expc/db2/linuxamd64/install/libdb2osse_install.so: Cannot create symlink to `libdb2osse_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libdb2locale.so: Cannot create symlink to `libdb2locale.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2sec_install.so: Cannot create symlink to `libdb2sec_install.so.1': Protocol erro
r
==> default: tar: expc/db2/linuxamd64/install/libdb2genreg_install.so: Cannot create symlink to `libdb2genreg_install.so.1': Protoco
l error
==> default: tar: expc/db2/linuxamd64/install/libdb2isys.so: Cannot create symlink to `libdb2isys.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2locale_install.so: Cannot create symlink to `libdb2locale_install.so.1': Protoco
l error
==> default: tar: expc/db2/linuxamd64/install/libdb2dstf_install.so: Cannot create symlink to `libdb2dstf_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libdb2g11n_install.so: Cannot create symlink to `libdb2g11n_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libinpro_install.so: Cannot create symlink to `libinpro_install.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2jcc.so: Cannot create symlink to `libdb2jcc.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/bin/locale: Cannot create symlink to `../install/locale': Protocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/install/locale: Cannot create symlink to `../../../install/locale': Pro
tocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/db2usrinf: Cannot create symlink to `../../../bin/db2usrinf': Proto
col error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/db2langdir: Cannot create symlink to `../../../bin/db2langdir': Pro
tocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/disp_msg: Cannot create symlink to `../../../bin/disp_msg': Protoco
l error
==> default: tar: Exiting with failure status due to previous errors
==> default: install_db2.sh: ERROR: unpacking gzipped installation tarball
==> default: ---- End output of /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl ----
==> default: Ran /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl returned 1
==> default: [2015-07-11T12:50:56+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit c
ode 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Logging into the VM and running the DB2 installer (./install_db2.sh`) gets DB2 installed.

**Comment by javornikolov** [comment]
My bad - I forgot to update Cheffile.lock in PR #390.
