### ISSUE TITLE
Long object name in Teradata

### ISSUE THREAD

**Issue by z0diak** [dbfit/dbfit#400]
Hi,

Found problem using long object names in DBFit tests. Long = 30+ characters.
Test to reproduce problem (on tables, but e.g. Execute Procedure fails with same problem):
```|Import|
|dbfit.fixture|

Connect in Teradata mode:
|Database Environment|teradata|
|Connect|jdbc:teradata://192.168.31.139/USER=dbc,PASSWORD=dbc,TMODE=TERA|

|Execute Ddl|CREATE TABLE dftest.t12345678_123456789_123456789_123456789 (field1 number)|

|Insert|dftest.t12345678_123456789_123456789_123456789|
|field1|
|1|

|Execute Ddl|CREATE TABLE dftest.t12345678_123456789 (field1 number)|

|Insert|dftest.t12345678_123456789|
|field1|
|1|

|Execute Ddl|DROP TABLE dftest.t12345678_123456789_123456789_123456789|
|Execute Ddl|DROP TABLE dftest.t12345678_123456789|
```

First "Insert" fails with: java.sql.SQLException: Cannot retrieve list of columns for dftest.t12345678_123456789_123456789_123456789 - check spelling and access rights
Second "Insert" succeeds 

Problem: Before Teradata 14.0 (not sure) object name (tables, procedures, views etc) must be less 31 characters. But starting from 14.0 version 30+ character object names are allowed.
I assume DbFit uses dbc.tables dictionary to get list of columns etc. dbc.tables shrinks object name to 30. That is how it works. Meanwhile dbc.tablesv display all names (including long) correctly. So I assume adding "v" to metadata request should solve the issue. 

P.S. Problem proved for: Teradata 14.0, JDBC Driver 14.10, JDBC Driver 14.11, JDBC Driver 15.0

**Comment by javornikolov** [comment]
Hi @z0diak, thank you for reporting this issue. If we change it to fetch the metadata using `tablesv` - would that still work on earlier versions of Teradata?

**Comment by z0diak** [comment]
@javornikolov yes, it will work for all currently supported versions (13.10+), and as far as I concerned it also must work with 12 version also. 
Any version below is not supported by vendor, I don't think we could find someone innovative enough to use DbFit but still sitting on those old TD versions :)

**Comment by MMatten** [comment]
I think we'd also need to use `dbc.columnsv` too. 

@z0diak - Can you check that this presents the long form of column and SPL parameter names?
Do you know if these 2 DBC views are available in Teradata 12?

**Comment by z0diak** [comment]
@MMatten good point, columnsv also. 
Yes, according to TD 12 Data Dictionary documentation (http://www.info.teradata.com/templates/eSrchResults.cfm?prodline=&txtpid=&txtrelno=&txtttlkywrd=TDBS12.0&rdsort=Title&srtord=Asc&nm=Teradata+Database+12.0) dbc.columns and dbc.tables are deprecated since TD 12, and dbc.columnsv and dbc.tablesv are introduced as replacement since TD 12.

**Comment by MMatten** [comment]
@javornikolov if you want to pick up this one I can test it on Teradata 13.10 and 14. Or I can pick it up.

**Comment by javornikolov** [comment]
@MMatten, you can pick it - I think we only need to change the names of the data dictionary views/tables which we're using to fetch the metadata.

**Comment by javornikolov** [comment]
Hi @z0diak [here](https://s3.amazonaws.com/dbfit/artifacts/71451580/71451581/dbfit-complete-3.1.0.zip) is a test version which is supposed to fix the issue. Could you test to make sure it's working OK?

**Comment by z0diak** [comment]
@javornikolov works fine, thank you
