### ISSUE TITLE
Add support for MySQL TINY/MEDIUM/LONGTEXT data types

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#424]
See forum request at https://groups.google.com/forum/#!topic/dbfit/u0yw2sZ8f64.

**Comment by MMatten** [comment]
I've added support in branch `support-mysql-xTEXT-data-types`. @javornikolov would you be able to create a test build/download for the forum user again?

**Comment by javornikolov** [comment]
@MMatten, the travis-ci build runs automatically and artifacts are uploaded to s3. The relevant IDs for the download URL can be found in the build log (it can be found at https://travis-ci.org/).

**Comment by eohehir** [comment]
Hi @MMatten and @javornikolov,

I had a look at https://travis-ci.org/dbfit/dbfit/builds/80909312 and can that a build for the support-mysql-xTEXT-data-types completed successfully and a zip file was uploaded to artifacts/80909312/80909314/dbfit-complete-3.2.1-SNAPSHOT.zip.

Not sure if I can access this or even where to find the zip file.  Is this something I download from travis-ci ?

Thanks,

Eoin.

**Comment by MMatten** [comment]
You can get at the ZIP file from: https://s3.amazonaws.com/dbfit/artifacts/80909312/80909313/dbfit-complete-3.2.1-SNAPSHOT.zip

Mark

**Comment by MMatten** [comment]
Or indeed https://s3.amazonaws.com/dbfit/artifacts/80909312/80909314/dbfit-complete-3.2.1-SNAPSHOT.zip (this one was built with Java 8, the one above was built with Java 7).

**Comment by eohehir** [comment]
Thanks @MMatten . I'll download the Java 7 version and run my suite against it. Cheers.

**Comment by MMatten** [comment]
@eohehir please let us know if it's working correctly, when you can, so that we can close down this issue.
