### ISSUE TITLE
Query about DbFit Password prompt

### ISSUE THREAD

**Issue by EdanGallagher** [dbfit/dbfit#446]
Hi all,
I'm currently looking at migrating my ETL validation scripts from a CMD batch file setup to a test suit within DbFit.

Our company policy is that no plain text passwords can be stored on our servers.

I was looking into the encrypt utility as a way around this; however, as users would still be able to gain access to our DB when using the encrypted key I was wondering if there is a way to prompt the user for the password prior to connecting to the DB during the tests?

Also, when considering numerous tests contained within a test suit, is it possible to prompt for the password which could be held within memory for the duration of the test suite execution and cleared after. Meaning that the user would only be prompted once and each of the tests would get the password from memory to be called by each test?

Any help would be greatly appreciated.

Thanks,
Edan

**Comment by javornikolov** [comment]
There is no password prompt support at the moment.

But maybe there is another solution - if your DbFit is running on a secured server:
* You can ensure that the encryption key is not accessible for users. Without the encryption key, it won't be possible to decrypt the password. 
* You can also use `ConnectUsingFile` and put the connection properties file in a place which is not accessible for users. (So even the encrypted password won't be accessible for them)

**Comment by EdanGallagher** [comment]
Hi Yavor,

Thanks for the reply! Yes I ran that by our security manager and it doesn't seem to be a runner.
On the encryption utility I was having an issue in that when I was using the key in the connection string it seemed to be passing the key rather than the password from the registry.

Do I need to specify the registry location or should the password be retrieved automatically?

Also can you use the key in the connection string like this:

connection-string=jdbc:sqlserver://0000000\test;databaseName=test;user=test;password=en(XXX)

or will it only work when specifying the properties separately?

Thanks again,
Edan

**Comment by EdanGallagher** [comment]
Hi Yavor,

Just on the above not, I'm using the ConnectUsingFile method with the connection string.

Thanks again,
Edan

**Comment by javornikolov** [comment]
> On the encryption utility I was having an issue in that when I was using the key in the connection string it seemed to be passing the key rather than the password from the registry.

I'm not sure I'm getting what you mean. Could you try to clarify? DbFit will take the connection string, decrypt the password if it's in ENC(..) format using the encryption key from the Java keystore: and will proceed with connecting to the database.

> Do I need to specify the registry location or should the password be retrieved automatically?
There is a default location of the Java keystore which is being used. That location is platform specific but in general - it's in user's home (http://stackoverflow.com/questions/8980364/how-do-i-find-out-what-keystore-my-jvm-is-using)

> connection-string=jdbc:sqlserver://0000000\test;databaseName=test;user=test;password=en(XXX) or will it only work when specifying the properties separately?

Good question - currently it only works when the password is in separate attribute.

**Comment by EdanGallagher** [comment]
Hi Yavor,

Thanks for that! In relation to the first point, it seemed that when I included the encryption key in the connection string format in my config file, I received an incorrect logon details error message. Based on that I was assuming that the ENC(XXX) value was being sent in plain text rather than the password.

I'll try this again using the separate properties method and let you know how I get on.

Thanks again for your help,
Edan

**Comment by EdanGallagher** [comment]
Hi Yavor,

Quick question in relation to specifying the connection properties separately in the config file.
I'm getting an error when I attempt to logon with the config file as follows:

service=//00.000.00.000\XXX
username=name
password=ENC(xxxxxxxxxxxxxxxxxxxx)
database=test

Using the following script:

!path lib\*.jar
!|dbfit.SqlServerTest|
!|Import| |dbfit.fixture|
!|Connect using file|DatabaseConnection.config|
!|Query| select count(*) from dbo.TEST|
||
|1000|

This is the error returned:

"com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host //00.000.00.000, named instance XXX has failed."

Error: "java.net.UnknownHostException: //00.000.00.000". Verify the server and instance names, check that no firewall is blocking UDP traffic to port 1434, and for SQL Server 2005 or later verify that the SQL Server Browser Service is running on the host.

Whereas the connection works fine when I specify the connection string as:

connection-string=jdbc:sqlserver://00.000.00.000\XXX;databaseName=test;user=name;password=password

Can you see if I've omitted anything (I'm assuming there may be an issue with how I'm defining the service?)?

Any help would be greatly appreciated.

Thanks again,
Edan

**Comment by javornikolov** [comment]
There are some examples at: http://dbfit.github.io/dbfit/docs/reference.html and http://dbfit.github.io/dbfit/docs/database-specific-information.html#microsoft-sql-server (perhaps may be found in the mailing list too).

I guess there the `//` prefix should be removed
```
service=00.000.00.000\XXX
```

**Comment by EdanGallagher** [comment]
Thanks Yavor, 

That did the trick alright! I've removed the prefix and the connection is working fine now :)

Thanks again for all your help!
Edan
