### ISSUE TITLE
Support for multiline execute statements

### ISSUE THREAD

**Issue by spilja** [dbfit/dbfit#492]
Add support for executing multiline statements. Wrapping in !- -! doesn't seem to do the trick.

**Comment by MMatten** [comment]
I think this does work. Can you please provide a failing example?

**Comment by spilja** [comment]
You're right, it does work. I had a problem with a long merge statement, I kept getting invalid column index exception even though the statement was fine. However, setting

    `|set option|bind symbols|false|`

prior to my execute statement cleared up the problem.
