### ISSUE TITLE
SSL connections with Redshift (Postgres)

### ISSUE THREAD

**Issue by nmcbride1** [dbfit/dbfit#494]
Hi,
We've been using DbFit very successfully with Redshift for a while now. However, we recently switched on the functionality to only allow SSL connections. Is there a way to define this in the db connection file?

The error we now get is:

org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "", user "", database "", SSL off

Thanks!

**Comment by javornikolov** [comment]
I haven't tried postgresql SSL connections but here I can see some hints: https://jdbc.postgresql.org/documentation/94/ssl-client.html

And here are some references which may help if java parameters need to be set: http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.CustomizingTestExecution

**Comment by nmcbride1** [comment]
Got it working. Solution if anyone needs it:

- download the official Redshift JDBC driver (http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html#download-jdbc-driver)

- create a connection string such as the following and put it in the configuration file:

connection-string=<cluster endpoint>/<db>?user=<username>&password=<password>&ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory

Note that the sslfactory setting is telling it that a certificate is not in place so although the channel is encrypted you are not authenticating that you are connecting to who you want it to.

More info here:

http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html#connecting-ssl-support-java

Neil
