### ISSUE TITLE
Could not find fixture: dbfit.TeradataTest.

### ISSUE THREAD

**Issue by samiulanik** [dbfit/dbfit#501]
I am having problem with dbfit with teradata. I have tried following in the HelloWorld page

```
!path lib/*.jar
|Import|
|dbfit.fixtures|
!|dbfit.TeradataTest|
!|Connect|jdbc:teradata://IP_Address /USER=U,PASSWORD=p,DATABASE=db_name,TMODE=ANSI,CHARSET=ASCII|
```

When I try to run I get Could not find fixture: dbfit.TeradataTest. and Could not find fixture: Connect. error.
I am using Teradata jdbc driver 15.10 (Also tried 15.00). Both terajdbc4.jar and tdgssconfig.jar are copied in the lib folder mentioned in the path.

**Comment by javornikolov** [comment]
Could you try just leaving a blank line instead of the following two ones:
```
|Import|
|dbfit.fixtures|
```

**Comment by MMatten** [comment]
@samiulanik can we assume this is now resolved?

**Comment by samiulanik** [comment]
yes. it has been resolved.

**Comment by MMatten** [comment]
Thanks for confirming.
