### ISSUE TITLE
Add Oracle support to the Travis CI build

### ISSUE THREAD

**Issue by javornikolov** [dbfit/dbfit#503]
Here is an example how this has been done in another project: https://github.com/rsim/ruby-plsql/pull/103

**Comment by MMatten** [comment]
That looks interesting. The instructions suggest that the Oracle installer needs to be downloaded (and checked in) but then there's some code to download it via controlling a web browser windows. Do you know how it works?

Do you know how much additional time this adds to a build?

I think we could do something similar for Informix too.

**Comment by javornikolov** [comment]
I think it adds a few minutes (maybe between 1 and 3). The nastier thing is that it requires legacy VM on Travis side (due to the `root`/`sudo`requirements), which leads to some other limitations and inefficiencies (and possibly delay until such VM is dedicated for a triggered build).

At some point I played a bit with [Circle CI](https://circleci.com/) where I had I feeling it may be more efficient for such kind of environment (e.g. no such `legacy` flagging when using `docker`).
