### ISSUE TITLE
Missing stored procedure and function execution for HSQLDB

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#529]
Stored procedure and function execution has not been implemented in the HSQLDB DbFit adapter.

This also prevents adding stored proc / function tests to the `CoreTests` hence we have duplicate tests under `FitnesseRoot`.

**Comment by MMatten** [comment]
A complication with implementing this is that HSQLDB doesn't support the regular function execution syntax as in `PreparedStatements`.

Return values need to be retrieved via a `ResultSet` rather than an out parameter.

I guess creating a custom `StatementExecution` variant, as per the Informix adapter, would be the way to go on this. 

@javornikolov any different thoughts?

**Comment by MMatten** [comment]
As we did for the Informix implementation, adding 

`StatementExecution createFunctionStatementExecution(PreparedStatement statement);`

to the `DBEnvironment`, might we consider adding a

`String buildFunctionCall(String procOrFuncName, int numberOfParameters)`? Or maybe a better name such as `buildFunctionCallStatementText`.

**Comment by MMatten** [comment]
Perhaps an alternative would be to actually execute functions via a query and retrieve the output via a `ResultSet`.

This could be useful to make it generic for #520.

**Comment by javornikolov** [comment]
> As we did for the Informix implementation, adding
> 
> StatementExecution createFunctionStatementExecution(PreparedStatement statement);
> 
> to the DBEnvironment, might we consider adding a
> 
> String buildFunctionCall(String procOrFuncName, int numberOfParameters)? Or maybe a better name such as buildFunctionCallStatementText.

Maybe we have some attempts in that direction, could what we have in #463 be of some help?

**Comment by javornikolov** [comment]
A bit too general as of now but it's possible a database to lack support for stored procedures (e.g. SQLite I think is like that).

**Comment by MMatten** [comment]
> Maybe we have some attempts in that direction, could what we have in #463 be of some help?

That's a big PR. Do you think it's worth trying to finish it or just pick out som us dil ideas now?

**Comment by javornikolov** [comment]
Indeed, it's a big experimental PR. Perhaps we don't need to try to finish it now (unless it helps us to move faster for some reason).

I think we ended up here while trying to fix #490 - do we need HSQLDB stored proc support to deal with it?

**Comment by MMatten** [comment]
> A bit too general as of now but it's possible a database to lack support for stored procedures (e.g. SQLite I think is like that).

Yes, I thought we'd hit it at some point so maybe not best to put proc/function tests into the `CoreTests` suite. I wanted to get more uniformity across the adapters before addressing #490 as I was going to look to get this working across all DB types not just Oracle.

**Comment by javornikolov** [comment]
Maybe it's still possible to have tests for adapters with `stored procs` support in a common place.

**Comment by MMatten** [comment]
Yes, adding tests to:

FitNesseRoot/DbFit/AcceptanceTests<https://github.com/dbfit/dbfit/tree/master/FitNesseRoot/DbFit/AcceptanceTests>/LibraryTests

Would be the place then include or symlink them.

Sent from my iPhone

On 19 Dec 2016, at 13:47, Yavor Nikolov <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe it's still possible to have tests for adapters with stored procs support in a common place.

-

**Comment by MMatten** [comment]
Resolve by #554.
