### ISSUE TITLE
unable to connect to hive database through pycharm

### ISSUE THREAD

**Issue by kameshM** [dbfit/dbfit#570]
HI, I am trying to connect to hive database through pycharm but not able to do it.
![image](https://cloud.githubusercontent.com/assets/25765606/25339722/87a6485e-28fb-11e7-872f-4c8b2372248c.png)
can any one please help me here, I have installed sasl,thrift_sasl,pyhive but still not able to resolve it

**Comment by MMatten** [comment]
This doesn't sound like an issue related to DbFit. 

I'm guessing we can close it.
