### ISSUE TITLE
Fix failing CoreTests for Netezza

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#578]
Related to #565 

Requires new unified `CalcLength` stored routine, etc.

**Comment by javornikolov** [comment]
I'm not sure it would be possible to have really unified test for symbols unless we figure out how to simulate OUT parameters for Netezza.

It might be easier to rather let Netezza have a custom version of that test. I'm not quite sure how yet...

**Comment by MMatten** [comment]
Something crazy like define the fixture contents from a FitNesse variable and override it in the Netezza suite. 

Or the `LibraryTests` route. I.e. Move it out of the core suite and include/ symlink it in the other adapter suites.
