### ISSUE TITLE
Java 7 build fails on Travis-CI (missing OracleJDK7 on Ubuntu image)

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#592]
Transfer of issues from #591

**Comment by javornikolov** [comment]
A possible workaround might be switch to openjdk **and** change gradle wrapper url scheme from `https` to `http`.

**Comment by MMatten** [comment]
@javornikolov any downsides to implementing your idea?

Also downgrading the JDK version to u55 seems to work ok too (though more work to revert it if Ubuntu publish another certified version in their package repos):-

https://github.com/dbfit/dbfit/compare/build-with-openjdk7-not-oraclejdk7

I think the failure is an issue with u131 but the only earlier version I can find to install on Ubuntu's repo is u55. May be there's another Debian package repo somewhere with later ones.

**Comment by javornikolov** [comment]
As soon as gradle is reachable by http I don't think there are any issues with that workaround.

**Comment by MMatten** [comment]
Great. Are you planning to create a PR from your branch?

**Comment by javornikolov** [comment]
> Great. Are you planning to create a PR from your branch?

#593
