### ISSUE TITLE
dbfit connection error

### ISSUE THREAD

**Issue by krishabh85** [dbfit/dbfit#638]
Please suggest me the suitable drivers and jar files to rectify the issue.

java.lang.IllegalArgumentException: DB Environment not supported:Oracle 	at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:99) 	at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106) 	at dbfit.OracleTest.(OracleTest.java:5) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 	at java.lang.reflect.Constructor.newInstance(Unknown Source) 	at java.lang.Class.newInstance(Unknown Source) 	at fit.FixtureClass.newInstance(FixtureClass.java:24) 	at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:61) 	at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:82) 	at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:43) 	at fit.Fixture.loadFixture(Fixture.java:142) 	at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:134) 	at fit.Fixture.doTables(Fixture.java:79) 	at fit.FitServer.process(FitServer.java:81) 	at fit.FitServer.run(FitServer.java:56) 	at fit.FitServer.main(FitServer.java:41)
--

**Comment by MMatten** [comment]
Support issues should be logged at the support dbfit google group please.

**Comment by MMatten** [comment]
Also, please add your test page source in the query there.

**Comment by krishabh85** [comment]
In my office system, I do not have the access to the google groups, Kindly help me out here only.
Thanks

> Support queries are better asked at the support dbfit google group please.

**Comment by MMatten** [comment]
Without your test page source to look at I can’t tell what the problem is.

**Comment by krishabh85** [comment]
I just need the link to download the file dbfit-oracle-3.2.0.jar as I am not able to find it in the central repository.
Thanks.

**Comment by MMatten** [comment]
Please use the support forum on google groups.
