### ISSUE TITLE
Exception throwing on a simple DBFit Test

### ISSUE THREAD

**Issue by krishabh85** [dbfit/dbfit#639]
I am passing a simple DBFit Test on my Oracle Database but it is throwing some exception and no assertion is made. Kindly, help me out please.
My code is :
!path lib/*.jar
!|dbfit.OracleTest|
!|Connect|mtxuatdb01.fr.world.socgen:1533|username|*********(password)|*****|
|Query| SELECT 100 AS 'ID', 'Bob' AS 'Name' UNION SELECT 102 AS 'ID', 'Sally' AS 'Name' |
|ID|Name|
|100|Bob|
|103|Jane|

**Comment by javornikolov** [comment]
Please add blank lines before and after `!lConnectl...` line and try again.
