### ISSUE TITLE
DB Fit for Oracle 12c

### ISSUE THREAD

**Issue by vinayak115** [dbfit/dbfit#672]
Hi, I wanted to know if DB fit will provide Support for 12C Version. We have forced encryption enabled in our DB ENV. And I tried connecting to DB with OJDBC6-11.2.0.4.jar driver, but it gives me ORA-12650 connection Error. The same works on DB which do not have forced encryption.

Do you plan to upgrade DBfit which will support 12C database with forced encryption?

**Comment by javornikolov** [comment]
I created #673 for addressing this.

Could you please try the build from this branch (https://s3.amazonaws.com/dbfit/artifacts/dbfit/dbfit/3204/3204.1/dbfit-complete-4.0.0-SNAPSHOT.zip) and JDBC version ojdbc8:19.3.0.0 (or anything >= 12.2 should be OK for new encryption algorithms).

CI tests are passing, maybe all incompatibilities have been resolved in the work related to migrating to JDK 8 but there might be some other things to be resolved.

**Comment by vinayak115** [comment]
Thank you! That worked :)
