### ISSUE TITLE
No TravisCI builds running

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#682]
TravisCI builds are no longer running for pushed commits and/or PRs.

Documentation here suggests that migration from TravisCI.org to TravisCI.com would be automatic:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

Perhaps this project needs to be registered with TravisCI.com (but I believe this has already been completed as I can see builds only 5 months old, here: https://app.travis-ci.com/github/dbfit/dbfit/builds/225388851).

**Comment by MMatten** [comment]
Perhaps there's no longer a free plan for OSS projects:
https://www.travis-ci.com/pricing/

I've reached out to them to find out what the situation is.

**Comment by MMatten** [comment]
@javornikolov are you able to re-connect this project back up to TravisCI? I'm not presented with an option to activate the DbFit project when I try this in Travis-CI.com.

**Comment by javornikolov** [comment]
![Screenshot_20211018-215246_Samsung Internet](https://user-images.githubusercontent.com/203471/137790109-95feee62-2798-434d-ba50-1f94cad176c5.jpg)

**Comment by javornikolov** [comment]
Hi @MMatten, after contacting Travis CI team we got more build credits which should allow us to restart our builds.
We we approach running out of credits we should contact them again to refill.
