### ISSUE TITLE
Insertion not working 

### ISSUE THREAD

**Issue by SreeKrishnaTheja** [dbfit/dbfit#692]
Hey I am using DBfit and I am trying to insert values into a already exxisting table.
It is not throwing up any error or exception but the row is not being created in the table.
Tried both with Execute query method and Insert method

![image](https://user-images.githubusercontent.com/62323108/144635685-7af9cd37-9b5a-46c9-a93b-a874bf3b718c.png)

**Comment by javornikolov** [comment]
Hi,

In what way do you check whether the row has been inserted or not?

Bare in mind that database rollback might be happening at the end of the
test page execution (the default behavior - as side effects are in general
unwanted). So, unless you explicitly commit - the changes will only be
visible within the tests in that page.

Best regards
Yavor

**Comment by SreeKrishnaTheja** [comment]
Thanks a lot @javornikolov  , It worked.
