### ISSUE TITLE
Broken link/missing version?

### ISSUE THREAD

**Issue by mattagape** [dbfit/dbfit#706]
Hi

On this page: http://dbfit.github.io/dbfit/
there is supposedly a link to "Download DbFit", supposedly 3.2.1 snapshot, but the link is broken.

Where can one find the latest version to execute on Linux? Is it recommended that one builds it from the source files?

Thank you

**Comment by javornikolov** [comment]
Hi, please go to latest successful build at https://github.com/dbfit/dbfit/actions - there are zip artifacts at the bottom.

Thanks for reporting the issue! We'll review the broken links and fix them.

**Comment by mattagape** [comment]
Thank you.

**Comment by javornikolov** [comment]
@mattagape - I have fixed some issues on the website. The download link there is working fine now. Thank you for pointing this issue out as there were some other problems as well.

From the link which I gave earlier you are getting recent builds from the main branch  (with changes which are not yet released):
> Hi, please go to latest successful build at https://github.com/dbfit/dbfit/actions - there are zip artifacts at the bottom.

I believe these builds are stable enough, yet - in case you face any issue, you may download official release builds from here as well: https://github.com/dbfit/dbfit/releases
