### ISSUE TITLE
How to use regular expressions in dbfit

### ISSUE THREAD

**Issue by forceedge01** [dbfit/dbfit#708]
This document shows that FitNesse supports regular expressions in decision tables http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ValueComparisons.

However when I tried this with the Execute Procedure command it errors out, trying to do a text comparison instead. Can you please advise?

Thanks

**Comment by javornikolov** [comment]
Fitnesse supports Fit and Slim testing frameworks. DbFit is currently based on Fit. The example which you refer to is based on Slim - maybe the regex feature is specific to it. Similar might be possible with Fit but I don't know if and how at the moment.

**Comment by forceedge01** [comment]
Thanks @javornikolov that makes sense. I didn't know about the 2 test frameworks. I had a quick look couldn't find anything but i'll have a thorough look and report back.
