### ISSUE TITLE
What is the exclamation mark for in dbfit commands?

### ISSUE THREAD

**Issue by forceedge01** [dbfit/dbfit#714]
Hello,

The documentation is not consistent with the exclamation mark. Same commands are used with and without the exclamation mark. I am wondering why this is used and is this documented somewhere?

Example from readme execute procedure:
```
Second row (applicable only if the procedure has parameters)
First example:

 !|Execute Procedure|ConcatenateStrings   |
 |first string|second string|concatenated?|
 |Hello       |World        |Hello World  |
 |Ford        |Prefect      |Ford Prefect |

Second example:

  |Execute Procedure|Multiply|
  |factor|val|val?           |
  |5     |10 |50             |

```

Thanks

**Comment by javornikolov** [comment]
There is a note about it in the docs here: https://dbfit.github.io/dbfit/docs/getting-started.html

FitNess framework sometimes applies some formatting and turns text to links, adding exclamation prevents such transformations.
