### ISSUE TITLE
Whitespace issue makes test fail, but html report does not highlight this.

### ISSUE THREAD

**Issue by forceedge01** [dbfit/dbfit#716]
Hello,

An assertion in dbfit is failing. This is due to whitespace as outlined in this issue https://stackoverflow.com/questions/8824227/fitnesse-cant-see-the-difference-between-the-expected-and-the-actual-result-in.

1. The solution would simply be to have space characters replaced with `&nbsp;` and then used in the html output. I am not sure where to make this change though.

2. I can see the diff in an xml report running the cli tool, the problem is that xml is difficult to read. What other formatters are available besides xml and text? I can't find documentation around this, text is repeatedly being used in one doc unhelpfully.

When executing tests via CLI I pass in "TestSuite?test&format=xml", is there another formatter that shows the failing text without all the xml fluff?

Thanks

**Comment by javornikolov** [comment]
This is rather a question to FitNesse framework

Also it's possible some additional tools to automate reformatting the output.

**Comment by forceedge01** [comment]
Fair play, i'll close this.
