### ISSUE TITLE
Oracle JRE only?

### ISSUE THREAD

**Issue by SpokeyWheeler** [dbfit/dbfit#729]
The documentation mentions getting the JRE from the Oracle Java home page. Is OpenJDK not supported? It seems to work (so far!)

**Comment by javornikolov** [comment]
If it works for you, OpenJDK should be fine. There might be some caveats (or not) with setting up the encryption functionality if you're using such (https://dbfit.github.io/dbfit/docs/dbfit-features.html#database-password-encryption). If you're  facing any specific issues with OpenJDK, please report.

**Comment by SpokeyWheeler** [comment]
Thank you!
